# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Official

# run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on: 
  push:
    branches: [ "master", "dev" ]

env:
  GB_NUGET_TOKEN: ${{secrets.GB_NUGET_TOKEN}}
  SYZERO_CORE_BRANCH: dev1.1.3

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: syzero-openai-service

      - name: Checkout syzero-core repo
        uses: actions/checkout@v3
        with:
          repository: winter2048/syzero-core
          path: syzero-core
          ref: ${{ env.SYZERO_CORE_BRANCH }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ./syzero-openai-service/src/SyZero.OpenAI.sln

      - name: Build
        run: dotnet build --configuration Release ./syzero-openai-service/src/SyZero.OpenAI.sln --no-restore

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            ./syzero-openai-service/src/SyZero.OpenAI.Web/bin/*

  pushImage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: harbor.syzero.com
          username: ${{ secrets.HARBOR_DOCKERHUB_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKERHUB_TOKEN }}

      - name: Build and push (master)
        uses: docker/build-push-action@v4
        if: github.ref_name == 'master'
        with:
          context: ./Release/net6.0/
          push: true
          tags: |
            harbor.syzero.com/syzero/syzero.openai:latest
            harbor.syzero.com/syzero/syzero.openai:${{ github.run_number }}

      - name: Build and push (dev)
        uses: docker/build-push-action@v4
        if: github.ref_name == 'dev'
        with:
          context: ./Release/net6.0/
          push: true
          tags: |
            harbor.syzero.com/syzero/syzero.openai:dev
            harbor.syzero.com/syzero/syzero.openai:${{ github.run_number }}-dev